export default {
    defaultLinkColor: '#a9a9a9',
    defaultNodeColor: '#d3d3d3',
    defaultNodeSize: 150,
    defaultNodeSymbolType: 'circle',
    defaultTextSize: 10, // in px
    graphAutomaticArrangeOnNodeDrag: false,
    height: 500,
    highlightColor: 'blue',
    highlightOpacity: 0.1,
    labelProperty: 'uid',
    maxBaseNodeSize: 36,
    maxScore: 1,
    maxStroke: 4.5,
    maxZoom: 7,
    minScore: 0,
    minZoom: 0.1,
    nodeFixedAfterDropped: true,
    nodeStrokeColor: 'green',
    nodeStrokeWidth: 1.5,
    nodeMouseCursor: 'pointer',
    nodeOpacity: 1,
    nodeLabelDefaultDx: 85,
    linkStrokeWidth: 1.5,
    linkOpacity: 1,
    width: 1000
};
