export default {
    defaultLinkColor: '#a9a9a9',
    defaultNodeColor: '#d3d3d3',
    defaultNodeSize: 8,
    defaultNodeSymbolType: 'circle',
    defaultTextSize: 10,
    height: 500,
    highlightColor: 'blue',
    highlightOpacity: 0.1,
    labelProperty: 'uid',
    maxBaseNodeSize: 36,
    maxScore: 1,
    maxStroke: 4.5,
    maxTextSize: 24,
    maxZoom: 7,
    minScore: 0,
    minZoom: 0.1,
    nodeFixedAfterDropped: true,
    nodeLabelTextCenter: false,
    outline: false,
    strokeThickness: 1.5,
    width: 960
};
